trigger:
- master

variables:
  BASE_URL: 'https://www.saucedemo.com'

jobs:

- job: Smoke
  displayName: 'Smoke Tests'

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - checkout: self
    displayName: 'Checkout repository'

  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: '24.x'

  - script: |
      node --version
      npm --version
    displayName: 'Verify Node.js and npm'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright browsers'

  - script: npm run test:smoke
    displayName: 'Run Smoke Tests'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Smoke Report'
    condition: always()
    inputs:
      targetPath: 'playwright-report'
      artifact: 'smoke-report'


- job: Regression
  displayName: 'Regression Tests'

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - checkout: self
    displayName: 'Checkout repository'

  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: '24.x'

  - script: |
      node --version
      npm --version
    displayName: 'Verify Node.js and npm'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright browsers'

  - script: npm run test:regression
    displayName: 'Run Regression Tests'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Regression Report'
    condition: always()
    inputs:
      targetPath: 'playwright-report'
      artifact: 'regression-report'